// Thèmes et paires de mots (façon shorts Sunroof)
// Chaque paire : deux mots proches — l'un pour les Civils, l'autre pour l'Undercover (tiré au sort).
const THEMES = [
  {
    id: "duos",
    name: "Duos de légende",
    emoji: "👯",
    pairs: [
      ["PNL", "Bee & A"],
      ["Batman & Robin", "Astérix & Obélix"],
      ["Mario & Luigi", "Sonic & Tails"],
      ["Naruto & Sasuke", "Goku & Vegeta"],
      ["Tic & Tac", "Timon & Pumbaa"],
      ["Daft Punk", "Justice"],
      ["Bigflo & Oli", "Djadja & Dinaz"],
      ["Fred & George Weasley", "Zig & Sharko"],
      ["Bonnie & Clyde", "Thelma & Louise"],
      ["Tom & Jerry", "Titi & Grosminet"],
    ],
  },
  {
    id: "rapfr",
    name: "Rap FR",
    emoji: "🎤",
    pairs: [
      ["Booba", "Kaaris"],
      ["Jul", "SCH"],
      ["Ninho", "Niska"],
      ["Nekfeu", "Orelsan"],
      ["Damso", "Hamza"],
      ["Gazo", "Tiakola"],
      ["PNL", "13 Block"],
      ["Aya Nakamura", "Wejdene"],
      ["Freeze Corleone", "Alpha Wann"],
      ["Soprano", "Black M"],
    ],
  },
  {
    id: "anime",
    name: "Anime & Manga",
    emoji: "🍥",
    pairs: [
      ["Killer Bee", "A (le Raikage)"],
      ["Kakashi", "Gaï"],
      ["Itachi", "Madara"],
      ["Goku", "Saitama"],
      ["Livaï", "Erwin"],
      ["Luffy", "Zoro"],
      ["Pikachu", "Raichu"],
      ["Ronflex", "Goinfrex"],
      ["Light Yagami", "L"],
      ["Tanjiro", "Zenitsu"],
    ],
  },
  {
    id: "foot",
    name: "Football",
    emoji: "⚽",
    pairs: [
      ["Messi", "Ronaldo"],
      ["Mbappé", "Haaland"],
      ["PSG", "OM"],
      ["Zidane", "Ronaldinho"],
      ["Benzema", "Giroud"],
      ["Ligue 1", "Premier League"],
      ["Coupe du Monde", "Ligue des Champions"],
      ["Pogba", "Kanté"],
      ["Arbitre", "VAR"],
      ["Penalty", "Coup franc"],
    ],
  },
  {
    id: "bouffe",
    name: "Bouffe",
    emoji: "🌮",
    pairs: [
      ["Kebab", "Tacos"],
      ["Pizza", "Burger"],
      ["Nutella", "Kinder Bueno"],
      ["McDo", "Burger King"],
      ["Couscous", "Tajine"],
      ["Raclette", "Fondue"],
      ["Croissant", "Pain au chocolat"],
      ["Sushi", "Poke bowl"],
      ["Crêpe", "Gaufre"],
      ["Coca", "Oasis"],
    ],
  },
  {
    id: "jv",
    name: "Jeux vidéo",
    emoji: "🎮",
    pairs: [
      ["Fortnite", "Warzone"],
      ["FIFA", "PES"],
      ["Minecraft", "Roblox"],
      ["GTA", "Red Dead Redemption"],
      ["Mario Kart", "Fall Guys"],
      ["PlayStation", "Xbox"],
      ["Zelda", "Elden Ring"],
      ["League of Legends", "Dota"],
      ["Among Us", "Undercover"],
      ["Twitch", "YouTube"],
    ],
  },
  {
    id: "cine",
    name: "Ciné & Séries",
    emoji: "🎬",
    pairs: [
      ["Harry Potter", "Le Seigneur des Anneaux"],
      ["Marvel", "DC"],
      ["Netflix", "Disney+"],
      ["Dark Vador", "Kylo Ren"],
      ["La Casa de Papel", "Lupin"],
      ["Titanic", "Avatar"],
      ["Squid Game", "Alice in Borderland"],
      ["James Bond", "Jason Bourne"],
      ["Shrek", "L'Âge de glace"],
      ["Stranger Things", "Wednesday"],
    ],
  },
  {
    id: "classique",
    name: "Classique",
    emoji: "🎲",
    pairs: [
      ["Plage", "Piscine"],
      ["Café", "Thé"],
      ["Avion", "Hélicoptère"],
      ["Lune", "Soleil"],
      ["Cinéma", "Théâtre"],
      ["Douche", "Bain"],
      ["Vélo", "Trottinette"],
      ["Hiver", "Automne"],
      ["Mariage", "Anniversaire"],
      ["Police", "Gendarmerie"],
    ],
  },
];
